export const VOLUMETRIC_DIVISOR = 5000;
export const STALE_LOCATION_THRESHOLD_MINUTES = 15;
export const DEFAULT_MAX_CONCURRENT_ORDERS = 5;
export const DEFAULT_PAGE_SIZE = 10;
export const MAX_PAGE_SIZE = 100;

export const ERROR_CODES = {
  INVALID_INPUT: 'INVALID_INPUT',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ZONE_NOT_FOUND: 'ZONE_NOT_FOUND',
  AREA_NOT_FOUND: 'AREA_NOT_FOUND',
  RATE_CARD_NOT_FOUND: 'RATE_CARD_NOT_FOUND',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  AGENT_NOT_AVAILABLE: 'AGENT_NOT_AVAILABLE',
  ASSIGNMENT_FAILED: 'ASSIGNMENT_FAILED',
  RESCHEDULE_NOT_ALLOWED: 'RESCHEDULE_NOT_ALLOWED',
  CANCEL_NOT_ALLOWED: 'CANCEL_NOT_ALLOWED',
  NOTIFICATION_FAILED: 'NOTIFICATION_FAILED',
  DUPLICATE_RESOURCE: 'DUPLICATE_RESOURCE',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
} as const;
